
name: Build and Publish Artifacts

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Install Fyne and OpenGL dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev xorg-dev pkg-config
      - name: Build Linux binary
        run: GOOS=linux GOARCH=amd64 make build
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: gopass-ui-linux
          path: bin/

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Build Windows binary
        run: |
          set GOOS=windows
          set GOARCH=amd64
          make build
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: gopass-ui-windows
          path: bin/

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Build macOS binary
        run: |
          export GOOS=darwin
          export GOARCH=arm64

          make build
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: gopass-ui-macos
          path: bin/
